### ISSUE TITLE
`java-emf-theia` project template fails to start

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#1176]
[...] I have now checked out the [glsp-examples/project-templates/java-emf-theia](https://github.com/eclipse-glsp/glsp-examples/tree/master/project-templates/java-emf-theia) example from github (master branch) and build the project from scratch.
I have exactly the same problem as within my own project. 

The Theia framework starts but the connection to the server failed (using the embedded server): 

![grafik](https://github.com/eclipse-glsp/glsp/assets/1339124/77bd0517-f142-4632-b1d3-cc3699ceb4a5)

The log file did not show much useful information:

```
$ yarn start
yarn run v1.22.19
$ yarn rebuild:browser && yarn --cwd tasklist-browser-app start
$ theia rebuild:browser
native node modules are already rebuilt for browser
$ theia start --TASKLIST_GLSP=5007 --root-dir=../workspace
Configuration directory URI: 'file:///home/rsoika/.theia'
2023-11-23T20:43:18.721Z root INFO Backend Object.initialize: 4.7 ms [Finished 0.228 s after backend start]
2023-11-23T20:43:18.721Z root INFO Backend Object.configure: 3.9 ms [Finished 0.228 s after backend start]
2023-11-23T20:43:18.721Z root INFO Backend MessagingContribution.onStart: 1.4 ms [Finished 0.228 s after backend start]
2023-11-23T20:43:18.721Z root INFO Backend OSBackendApplicationContribution.configure: 0.3 ms [Finished 0.242 s after backend start]
2023-11-23T20:43:18.721Z root INFO Backend LocalizationBackendContribution.initialize: 14.4 ms [Finished 0.242 s after backend start]
2023-11-23T20:43:18.721Z root INFO Backend LocalizationBackendContribution.configure: 0.2 ms [Finished 0.242 s after backend start]
2023-11-23T20:43:18.723Z root INFO Backend NodeFileUploadService.configure: 0.8 ms [Finished 0.243 s after backend start]
2023-11-23T20:43:18.723Z root INFO Backend FileDownloadEndpoint.configure: 1.2 ms [Finished 0.245 s after backend start]
2023-11-23T20:43:18.725Z root INFO Theia app listening on http://localhost:3000.
2023-11-23T20:43:18.726Z root INFO Backend DefaultWorkspaceServer.onStart: 6.7 ms [Finished 0.248 s after backend start]
2023-11-23T20:43:18.727Z root INFO Finished starting backend application: 0.0 ms [Finished 0.248 s after backend start]
2023-11-23T20:43:31.841Z root WARN Frontend CommonFrontendContribution.configure took longer than the expected maximum 100 milliseconds: 159.5 ms [Finished 1.187 s after frontend start]
2023-11-23T20:43:31.842Z root WARN A command editor.action.toggleStickyScroll is already registered.
2023-11-23T20:43:31.868Z root INFO Detected keyboard layout from browser API: German (PC)
2023-11-23T20:43:32.123Z root WARN Linked preference "workbench.colorCustomizations" not found. Source: "editor.bracketPairColorization.enabled"
2023-11-23T20:43:32.124Z root WARN Linked preference "window.titleBarStyle" not found. Source: "window.menuBarVisibility"
2023-11-23T20:43:32.155Z root WARN Frontend EditorNavigationContribution.onStart took longer than the expected maximum 100 milliseconds: 263.4 ms [Finished 1.513 s after frontend start]
2023-11-23T20:43:32.165Z root INFO Start frontend contributions: 514.9 ms [Finished 1.520 s after frontend start]
2023-11-23T20:43:32.166Z root INFO Changed application state from 'init' to 'started_contributions'.
2023-11-23T20:43:32.193Z root INFO Changed application state from 'started_contributions' to 'attached_shell'.
2023-11-23T20:43:32.193Z root INFO >>> Restoring the layout state...
2023-11-23T20:43:32.200Z root INFO <<< Nothing to restore.
2023-11-23T20:43:32.214Z root INFO Initialize the workbench layout: 22.2 ms [Finished 1.573 s after frontend start]
2023-11-23T20:43:32.215Z root INFO Changed application state from 'attached_shell' to 'initialized_layout'.
2023-11-23T20:43:32.225Z root ERROR [JsonrpcGLSPClient] Connection to server got closed. Server will not be restarted. []
2023-11-23T20:43:33.045Z root INFO Frontend application start: 1219.0 ms [Finished 14.566 s after backend start]
2023-11-23T20:43:33.045Z root INFO Replace loading indicator with ready workbench UI (animation): 828.0 ms [Finished 2.401 s after frontend start]
2023-11-23T20:43:33.046Z root INFO Changed application state from 'initialized_layout' to 'ready'.
```

When I check the browser console I think there is the more interesting information indicating that there was a problem with logger-protocol.ts

![grafik](https://github.com/eclipse-glsp/glsp/assets/1339124/9a937742-50fb-4b22-8a11-49f5c3f33277)

The corresponding method seems to be a kind of logger with nothing special:

```javascript
    export function log(name: string, logLevel: number, message: string, params: any[]): void {
        const console = consoles.get(logLevel) || originalConsoleLog;
        const severity = (LogLevel.strings.get(logLevel) || 'unknown').toUpperCase();
        const now = new Date();
        console(`${now.toISOString()} ${name} ${severity} ${message}`, ...params);
    }
```

The last days, when I tried to find the root of the problem, sometimes I stumbled over discussions about a missing write-access to some log files within the node.js  stack. And maybe this is  the root problem here that breaks everything. 

Have you ever heard from such a problem regarding Node.js on Linux Systems?
Note: It is not my system in general, as I can build and run my current official release. But my migration branch to GLSP 2.0 causes this kind of problem. It may be something with dependencies of external libraries.

_Originally posted by @rsoika in https://github.com/eclipse-glsp/glsp/discussions/1169#discussioncomment-7655124_

**Comment by rsoika** [comment]
Switching the theia version in the /java-emf-theia/glsp-client/ from `1.39.0`  to `1.43.1`  seems to solve the problem ....?
At least the tasklist demo is working on my machine now.

**Comment by planger** [comment]
Thanks for investigating this further, for me it behaves exactly as for you. Theia `1.39.0` can't connect to the Java GLSP server, whereas everything works fine with `1.43.1`.

**Comment by planger** [comment]
First we should update all project templates to use the latest version of Theia to avoid the problem.
Then let's investigate what is the root cause so that we support the two last Theia Community Releases.

**Comment by martin-fleck-at** [comment]
@planger I can upgrade the Theia version for the examples but I cannot reproduce the issue reported in this bug. 

- When using the `Launch TaskList Theia Backend (Embedded GLSP Server)` launch config, it simply works.
- When using the `Launch TaskList Theia Backend (External GLSP Server)` launch config, I had to manually ensure that my GLSP server in Eclipse starts on port 5007 (`-port 5007` as program argument) but then it works as well.

@tortmayr Any idea why that might be happening?

**Comment by planger** [comment]
Thanks for investigating this issue, @martin-fleck-at! Did you try to test it with `cd glsp-client && yarn start`?

**Comment by martin-fleck-at** [comment]
@planger I just tried it from the command line as you suggested and it is still working for me. I'll see what I can think of to "break" it.

**Comment by martin-fleck-at** [comment]
@planger I found the issue! Turns out it the problem happens when using Node 18 but with Node 20 it works without issues. I'll see if there is an easy workaround.

**Comment by planger** [comment]
Thanks for your PR.
Maybe this is unrelated, but when testing, I now got the following exception when trying to start the Java server :-/
```
2023-12-27T20:08:54.643Z root ERROR TaskList: ERROR StatusLogger Exception thrown by constructor for class org.apache.logging.log4j.core.impl.Log4jContextFactory
2023-12-27T20:08:54.643Z root ERROR TaskList:  org.apache.logging.log4j.plugins.di.NotInjectableException: No @Inject constructor or default constructor found for chain Key[type: org.apache.logging.log4j.core.lookup.InterpolatorFactory] -> Key[type: java.util.Map<java.lang.String, java.util.function.Supplier<org.apache.logging.log4j.core.lookup.StrLookup>>; namespace: Lookup]
2023-12-27T20:08:54.643Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.createDefaultFactory(DefaultInstanceFactory.java:132)
2023-12-27T20:08:54.643Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.lambda$getFactory$1(DefaultInstanceFactory.java:109)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.getFactory(DefaultInstanceFactory.java:109)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.InstanceFactory.getInstance(InstanceFactory.java:126)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.lambda$getArgumentFactory$7(DefaultInstanceFactory.java:204)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.lambda$registerBundleMethod$11(DefaultInstanceFactory.java:286)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.Binding.get(Binding.java:42)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.InstanceFactory.getInstance(InstanceFactory.java:115)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:189)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:41)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:91)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.core.impl.internal.InternalLoggerContext.<init>(InternalLoggerContext.java:47)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:58)
2023-12-27T20:08:54.644Z root ERROR TaskList: 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:64)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.spi.LoggingSystem.tryInstantiate(LoggingSystem.java:253)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.spi.LoggingSystem$SystemProvider.createLoggerContextFactory(LoggingSystem.java:300)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.spi.LoggingSystem.lambda$new$0(LoggingSystem.java:84)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.util.Lazy.lambda$map$0(Lazy.java:39)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.util.LazyUtil$SafeLazy.get(LazyUtil.java:115)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.spi.LoggingSystem.getLoggerContextFactory(LoggingSystem.java:171)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.LogManager.getFactory(LogManager.java:368)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:118)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:532)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.eclipse.glsp.server.launch.CLIParser.<clinit>(CLIParser.java:29)
2023-12-27T20:08:54.645Z root ERROR TaskList: 	at org.eclipse.glsp.example.javaemf.launch.TaskListServerLauncher.main(TaskListServerLauncher.java:34)
2023-12-27T20:08:54.645Z root ERROR TaskList: ERROR StatusLogger Log4j could not find a logging implementation. Please add log4j-core dependencies to classpath or module path. Using SimpleLogger to log to the console.
2023-12-27T20:08:54.692Z root ERROR TaskList: Exception in thread "main" java.lang.IllegalArgumentException: Invalid Configuration class specified
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:219)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:182)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:68)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.eclipse.glsp.server.utils.LaunchUtil.configureLogger(LaunchUtil.java:160)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.eclipse.glsp.server.utils.LaunchUtil.configureLogger(LaunchUtil.java:77)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.eclipse.glsp.server.utils.LaunchUtil.configure(LaunchUtil.java:68)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.eclipse.glsp.example.javaemf.launch.TaskListServerLauncher.main(TaskListServerLauncher.java:35)
2023-12-27T20:08:54.692Z root ERROR TaskList: Caused by: java.lang.reflect.InvocationTargetException
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:194)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	... 6 more
2023-12-27T20:08:54.692Z root ERROR TaskList: Caused by: org.apache.logging.log4j.plugins.di.NotInjectableException: No @Inject constructor or default constructor found for chain Key[type: org.apache.logging.log4j.core.lookup.InterpolatorFactory] -> Key[type: java.util.Map<java.lang.String, java.util.function.Supplier<org.apache.logging.log4j.core.lookup.StrLookup>>; namespace: Lookup]
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.createDefaultFactory(DefaultInstanceFactory.java:132)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.lambda$getFactory$1(DefaultInstanceFactory.java:109)
2023-12-27T20:08:54.692Z root ERROR TaskList: 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.getFactory(DefaultInstanceFactory.java:109)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.InstanceFactory.getInstance(InstanceFactory.java:126)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.lambda$getArgumentFactory$7(DefaultInstanceFactory.java:204)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.DefaultInstanceFactory.lambda$registerBundleMethod$11(DefaultInstanceFactory.java:286)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.Binding.get(Binding.java:42)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.plugins.di.InstanceFactory.getInstance(InstanceFactory.java:115)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:189)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	at org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration.<init>(BuiltConfiguration.java:50)
2023-12-27T20:08:54.693Z root ERROR TaskList: 	... 12 more
```

**Comment by martin-fleck-at** [comment]
@planger Interesting, I didn't encounter this before but now I do, I'll look into it.

**Comment by planger** [comment]
Thank you very much!
