### ISSUE TITLE
Exception when starting workflow server from fat jar

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#167]
```
java -jar org.eclipse.glsp.example.workflow-0.9.0-SNAPSHOT-glsp.jar org.eclipse.glsp.example.workflow.launch.ExampleServerLauncher
Exception in thread "main" java.lang.NoSuchFieldError: SPACING_NODE_SELF_LOOP
	at org.eclipse.elk.alg.layered.options.LayeredOptions.<clinit>(LayeredOptions.java:129)
	at org.eclipse.elk.alg.layered.options.LayeredMetaDataProvider.apply(LayeredMetaDataProvider.java:2155)
	at org.eclipse.elk.core.data.LayoutMetaDataService.registerLayoutMetaDataProviders(LayoutMetaDataService.java:160)
	at org.eclipse.glsp.layout.ElkLayoutEngine.initialize(ElkLayoutEngine.java:83)
	at org.eclipse.glsp.example.workflow.launch.WorkflowServerLauncher.main(WorkflowServerLauncher.java:38)
```

See https://github.com/eclipse-glsp/glsp-server/commit/41ef2ff1c3a8b41cdbac3dfc7265d8ff7d4fe023

**Comment by tortmayr** [comment]
Built with wrong parameters? `mvn clean verify -Pm2 -Pfatjar does work for me`

**Comment by planger** [comment]
Does it work for you to build and run the server when you in-comment the that I've out-commented here in the commit below?
https://github.com/eclipse-glsp/glsp-server/commit/41ef2ff1c3a8b41cdbac3dfc7265d8ff7d4fe023
I got the exception in the description of this issue when running the server.

**Comment by tortmayr** [comment]
Yes it does.  'mvn clean verify -Pm2 -Pfatjar' works without problems for me. Also uncommenting this line breaks the autolayouting so we should revert this commit

**Comment by tortmayr** [comment]
If I ommit the -Pm2 parameter I get the exception mentioned above.

**Comment by planger** [comment]
You're right, thanks! I updated the docs.
