### ISSUE TITLE
Minimal example should not require Visual Studio

### ISSUE THREAD

**Issue by dhendriks** [eclipse-glsp/glsp#502]
According to `glsp-examples/README.md`:

```
The web-based/client part of the examples has been developed using Visual Studio Code and the server/java part has been developed with the Eclipse IDE. However, it's of course also possible to use any other IDE or text editor.
```

However, when building the minimal example, Visual Studio does seem to be required:

```
// Started in: glsp-examples/minimal/client (master)
$ yarn
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
warning vscode-languageclient@6.1.3: The engine "vscode" appears to be invalid.
[4/5] Linking dependencies...
warning "@theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "@theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning "@theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "@theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning " > @wdio/mocha-framework@6.5.0" has unmet peer dependency "webdriverio@^6.0.1".
warning " > eslint-plugin-header@3.1.1" has incorrect peer dependency "eslint@>=7.7.0".
warning "workspace-aggregator-4be93672-e4b4-46f6-bf91-bfccd4d0a750 > @eclipse-glsp-examples/minimal-glsp > @eclipse-glsp/client > sprotty > snabbdom-virtualize@0.7.0" has incorrect peer dependency "snabbdom@~0.6.6".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
error <anonymized>\glsp-examples\minimal\client\node_modules\oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: <anonymized>\glsp-examples\minimal\client\node_modules\oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.22.8 | win32 | x64
gyp info find Python using Python version 3.7.3 found at "C:\ProgramData\Anaconda3\python.exe"
gyp http GET https://nodejs.org/download/release/v12.22.8/node-v12.22.8-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.22.8/node-v12.22.8-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.22.8/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v12.22.8/win-arm64/node.lib
gyp http GET https://nodejs.org/download/release/v12.22.8/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v12.22.8/win-x64/node.lib
gyp http 404 https://nodejs.org/download/release/v12.22.8/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v12.22.8/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v12.22.8/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.22.8/win-x64/node.lib
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (<anonymized>\glsp-examples\minimal\client\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at <anonymized>\glsp-examples\minimal\client\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (<anonymized>\glsp-examples\minimal\client\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at <anonymized>\glsp-examples\minimal\client\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at <anonymized>\glsp-examples\minimal\client\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at <anonymized>\glsp-examples\minimal\client\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at <anonymized>\glsp-examples\minimal\client\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "<anonymized_nodejs_dir>\\node.exe" "<anonymized>\\glsp-examples\\minimal\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd <anonymized>\glsp-examples\minimal\client\node_modules\oniguruma
gyp ERR! node -v v12.22.8
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

That does not seem to match with the statement from the README...

**Comment by tortmayr** [comment]
Hi @dhendriks,
This error comes from node-gyp which is used by Theia. Please make sure that you have the necessary [prerequisites for Theia installed](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites). This is also mentioned in the [README](https://github.com/eclipse-glsp/glsp-examples/blob/9fecbd3b907514901be359f777674851b0352cbf/README.md?plain=1#L14).
> The examples are heavily interwoven with Eclipse Theia, so please also check the prerequisites of Theia.

**Comment by dhendriks** [comment]
I don't see in the 'Theia prerequisites' that I must have Visual Studio installed...?

**Comment by tortmayr** [comment]
It's a little bit hidden in the Windows subsection (https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#building-on-windows).
You need the `windows-build-tools` or something equivalent in order to compile native node modules under windows.
It seems like the official Node.js for Windows installer can now also automatically install the required tools. That's likely a much better option than the module listed in the Theia prerequisites. (windows-build-tools).
![Selection_008](https://user-images.githubusercontent.com/2311075/149773790-3cf28d32-b5c1-4b0e-a19e-74fc528ce1c9.png)

**Comment by dhendriks** [comment]
The information is all very spread out...
