### ISSUE TITLE
Theia backend launch configuration not working reliably under Windows

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#666]
In some example repositories (e.g the node-json-theia/java-emf-theia project templates) the Theia backed debug launch config is not working when using Windows. Some bindings can not be found

```bash
C:\Program Files\nodejs\node.exe .\tasklist-browser-app\src-gen\backend\main.js --port=3000 --no-cluster --TASKLIST_GLSP=5007 --debug --app-project-path=C:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client/tasklist-browser-app --root-dir=C:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client/workspace
Debugger attached.
Error: No matching bindings found for serviceIdentifier: Symbol(RawProcessFactory)
    at _validateActiveBindingCount (c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\planning\planner.js:63:23)
    at _getActiveBindings (c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\planning\planner.js:49:5)
    at _createSubRequests (c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\planning\planner.js:92:26)
    at c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\planning\planner.js:116:17
    at Array.forEach (<anonymous>)
    at c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\planning\planner.js:115:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\planning\planner.js:95:20)
    at Object.plan (c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\planning\planner.js:137:9)
    at c:\Users\user\Documents\glsp-examples\project-templates\node-json-theia\glsp-client\node_modules\inversify\lib\container\container.js:333:37
````

Setting the `NODE_PRESERVE_SYMLINKS` environmental variable to false seems to fix the startup issues, however, then breakpoints in the backend source files are always considered unbound and will not be picked up.

**Comment by planger** [comment]
Isn't this fixed with https://github.com/eclipse-glsp/glsp/issues/777 too?
