### ISSUE TITLE
glsp-vscode-integration workflow example out of sync with glsp-server

### ISSUE THREAD

**Issue by kolovos** [eclipse-glsp/glsp#782]
Running the `Workflow GLSP Example Extension (External GLSP Server)` configuration of the latest version of the [workflow VS Code extension](https://github.com/eclipse-glsp/glsp-vscode-integration/tree/master/example/workflow), against the latest version of the [workflow GLSP server](https://github.com/eclipse-glsp/glsp-server/tree/master/examples/org.eclipse.glsp.example.workflow) produces a protocol mismatch exception on the server side, which suggests that the client and the server implementations may have fallen out of sync.

```
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Protocol version mismatch! The client protocol version '0.9.0' is not compatible with the server protocol version '1.0.0'!
	at org.eclipse.glsp.server.protocol.DefaultGLSPServer.validateProtocolVersion(DefaultGLSPServer.java:97)
	at org.eclipse.glsp.server.protocol.DefaultGLSPServer.initialize(DefaultGLSPServer.java:69)
	... 16 more
```

**Comment by tortmayr** [comment]
Hi @kolovos,
thanks for raising this issue. The problem should be fixed once this PR is reviewed and merged: https://github.com/eclipse-glsp/glsp-vscode-integration/pull/28
